global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['kafka-0:9090', 'kafka-1:9090', 'kafka-2:9090', 'kafka-second-0:9090']