spring:
  application:
    name: Shop
  banner:
    charset: UTF-8
  mandatory-file-encoding: UTF-8
  kafka:
    bootstrap-servers: 127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.Shop.*"
    streams:
      application-id: product-validation-stream
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.springframework.kafka.support.serializer.JsonSerde
        commit:
          interval:
            ms: 1000
        statestore:
          cache:
            max:
              bytes: 0
        spring:
          json:
            trusted:
              packages: "com.example.Shop.*"

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

app:
  kafka:
    forbidden-words: "запрещенный,паленый,контрбандный,неликвидный,нелегальный,бракованный"
    topics:
      input: products-input
      output: new_items
      rejected: rejected-items

jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    adjust-dates-to-context-time-zone: false